"""
Gate management commands.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

import click

from ..lib.gate_enforcer import GateEnforcer, GateValidationError


def get_sprint_path(sprint_id: str, output_dir: str = ".carby-sprints") -> Path:
    """Get the path to a sprint directory."""
    return Path(output_dir) / sprint_id


def load_sprint(sprint_id: str, output_dir: str = ".carby-sprints") -> tuple[dict[str, Any], Path]:
    """Load sprint metadata."""
    sprint_path: Path = get_sprint_path(sprint_id, output_dir)
    metadata_path: Path = sprint_path / "metadata.json"

    if not metadata_path.exists():
        raise click.ClickException(f"Sprint '{sprint_id}' not found.")

    with open(metadata_path, "r") as f:
        return json.load(f), sprint_path


def save_sprint(sprint_data: dict[str, Any], sprint_path: Path) -> None:
    """Save sprint metadata."""
    metadata_path: Path = sprint_path / "metadata.json"
    with open(metadata_path, "w") as f:
        json.dump(sprint_data, f, indent=2)


def generate_validation_token(sprint_id: str, gate_number: str, tier: int) -> str:
    """Generate a validation token for the gate."""
    token_id: str = str(uuid.uuid4())[:8]
    return f"val-tier{tier}-{token_id}"


def calculate_risk_score(sprint_data: dict[str, Any]) -> float:
    """
    Calculate risk score for the sprint.
    Returns a score between 0.0 (low risk) and 5.0 (high risk).
    """
    score: float = 0.0

    # Factor 1: Work item count
    work_item_count: int = len(sprint_data.get("work_items", []))
    if work_item_count > 20:
        score += 1.5
    elif work_item_count > 10:
        score += 0.75

    # Factor 2: Sprint duration
    duration: int = sprint_data.get("duration_days", 14)
    if duration < 7:
        score += 1.0  # Short sprints are riskier
    elif duration > 21:
        score += 0.5  # Long sprints accumulate risk

    # Factor 3: Gate status
    gates: dict[str, Any] = sprint_data.get("gates", {})
    failed_gates: int = sum(1 for g in gates.values() if g.get("status") == "failed")
    score += failed_gates * 0.5

    # Factor 4: Previous validation issues
    if sprint_data.get("validation_token"):
        score += 0.5

    return min(score, 5.0)


def generate_assumptions(sprint_data: dict[str, Any], gate_number: str, tier: int) -> str:
    """Generate assumptions document for the gate."""
    gate_names: dict[str, str] = {
        "1": "Planning Gate",
        "2": "Design Gate",
        "3": "Implementation Gate",
        "4": "Validation Gate",
        "5": "Release Gate",
    }

    assumptions: str = f"""# Assumptions for {gate_names.get(gate_number, f'Gate {gate_number}')}

**Sprint:** {sprint_data.get('sprint_id', 'Unknown')}
**Project:** {sprint_data.get('project', 'Unknown')}
**Gate:** {gate_number}
**Tier:** {tier}
**Generated:** {datetime.now().isoformat()}

## Assumed

1. All stakeholders have reviewed and approved the sprint plan
2. Work items are well-defined and achievable within the sprint duration
3. Required resources and dependencies are available
4. Risk assessment has been completed

## Validated

- [ ] Sprint goal is clear and measurable
- [ ] Work items are properly estimated
- [ ] Dependencies have been identified

## Requires Validation

- [ ] Technical approach review
- [ ] Resource allocation confirmation
- [ ] Timeline feasibility check

---
*Auto-generated by Carby Sprint CLI*
"""
    return assumptions


def check_gate_requirements(sprint_data: dict[str, Any], gate_number: str) -> tuple[bool, str | None]:
    """Check if gate requirements are met."""
    requirements: dict[str, dict[str, Any]] = {
        "1": {  # Planning Gate
            "required_status": ["initialized", "planned"],
            "needs_work_items": True,
            "description": "Sprint must be initialized and have work items planned",
        },
        "2": {  # Design Gate
            "required_status": ["planned"],
            "needs_work_items": True,
            "description": "Sprint must be planned",
        },
        "3": {  # Implementation Gate
            "required_status": ["running"],
            "needs_work_items": True,
            "description": "Sprint must be running",
        },
        "4": {  # Validation Gate
            "required_status": ["running"],
            "needs_work_items": True,
            "description": "Sprint must be running and work items in progress/completed",
        },
        "5": {  # Release Gate
            "required_status": ["running"],
            "needs_work_items": True,
            "description": "Sprint must be running with completed work items",
        },
    }

    req: dict[str, Any] | None = requirements.get(gate_number)
    if not req:
        return False, f"Unknown gate number: {gate_number}"

    current_status: str = sprint_data.get("status", "")
    if current_status not in req["required_status"]:
        return False, f"Sprint status is '{current_status}', required: {req['required_status']}"

    if req["needs_work_items"] and not sprint_data.get("work_items"):
        return False, "No work items planned"

    return True, None


@click.command()
@click.argument("sprint_id")
@click.argument("gate_number", type=click.Choice(["1", "2", "3", "4", "5"]))
@click.option(
    "--auto-generate",
    "-a",
    is_flag=True,
    help="Auto-generate assumptions document",
)
@click.option(
    "--output-dir",
    "-o",
    type=click.Path(),
    default=".carby-sprints",
    help="Directory containing sprint data",
)
@click.pass_context
def gate(
    ctx: click.Context,
    sprint_id: str,
    gate_number: str,
    auto_generate: bool,
    output_dir: str,
) -> None:
    """
    Pass a gate for the given SPRINT_ID.

    Gates:
      1 - Planning Gate: Validate sprint planning
      2 - Design Gate: Validate design decisions
      3 - Implementation Gate: Validate implementation approach
      4 - Validation Gate: Validate completed work
      5 - Release Gate: Validate release readiness
    """
    verbose: bool = ctx.obj.get("verbose", False)

    # Load sprint
    sprint_data, sprint_path = load_sprint(sprint_id, output_dir)

    # Validate gate using GateEnforcer
    enforcer = GateEnforcer(sprint_data)
    try:
        enforcer.validate_gate(gate_number)
    except GateValidationError as e:
        raise click.ClickException(str(e))

    # Calculate risk score
    risk_score: float = calculate_risk_score(sprint_data)

    # Determine validation tier based on risk
    tier: int
    if risk_score >= 3.0:
        tier = 2
        click.echo(f"⚠️  Risk score {risk_score:.1f}/5.0 requires Tier 2 validation")
    else:
        tier = 1
        if verbose:
            click.echo(f"Risk score {risk_score:.1f}/5.0 - Tier 1 validation")

    # Generate validation token
    validation_token: str = generate_validation_token(sprint_id, gate_number, tier)

    # Get gate info
    gates: dict[str, dict[str, Any]] = sprint_data.get("gates", {})
    gate_info: dict[str, Any] = gates.get(gate_number, {})

    # Update gate status
    gates[gate_number] = {
        "status": "passed",
        "name": gate_info.get("name", f"Gate {gate_number}"),
        "passed_at": datetime.now().isoformat(),
        "validation_token": validation_token,
        "tier": tier,
        "risk_score": risk_score,
        "forced": False,
    }
    sprint_data["gates"] = gates
    sprint_data["validation_token"] = validation_token
    sprint_data["risk_score"] = risk_score

    # Save gate record
    gate_record_path: Path = sprint_path / "gates" / f"gate_{gate_number}.json"
    with open(gate_record_path, "w") as f:
        json.dump(gates[gate_number], f, indent=2)

    # Auto-generate assumptions if requested
    if auto_generate or tier == 2:
        assumptions_path: Path = sprint_path / "gates" / f"gate_{gate_number}_assumptions.md"
        assumptions: str = generate_assumptions(sprint_data, gate_number, tier)
        with open(assumptions_path, "w") as f:
            f.write(assumptions)
        if verbose:
            click.echo(f"Generated assumptions: {assumptions_path}")

    # Update sprint status based on gate
    if gate_number == "1":
        sprint_data["status"] = "planned"
    elif gate_number == "5":
        sprint_data["status"] = "completed"
        sprint_data["completed_at"] = datetime.now().isoformat()

    save_sprint(sprint_data, sprint_path)

    click.echo(f"✓ Gate {gate_number} passed for sprint '{sprint_id}'")
    click.echo(f"  Token: {validation_token}")
    click.echo(f"  Tier: {tier}")
    click.echo(f"  Risk Score: {risk_score:.1f}/5.0")

    # Show next steps
    next_gate: str = str(int(gate_number) + 1)
    if next_gate in gates:
        click.echo(f"\nNext: carby-sprint gate {sprint_id} {next_gate}")
    elif gate_number == "5":
        click.echo(f"\nSprint completed! Archive with: carby-sprint archive {sprint_id}")
